# Generated by Django 5.0.7 on 2024-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Дата отчёта')),
                ('order_data', models.JSONField(verbose_name='Данные заказа')),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Расходы')),
            ],
        ),
    ]
