# Generated by Django 5.0.7 on 2024-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_products_alter_order_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(default=0.00, max_digits=10, decimal_places=2),
            preserve_default=False,
        ),
    ]
