# Generated by Django 5.0.7 on 2024-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_available_product_created_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
